name: Täglicher Datenimport nach MongoDB

on:
  schedule:
    - cron: '0 4 * * *' # Täglich um 4:00 UTC (also 6:00 Schweizer Zeit)
  workflow_dispatch: # Manuell auslösbar über GitHub UI

jobs:
  run-daily-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Umgebungsvariable für MongoDB setzen
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      - name: Starte das Scraping und lade nach MongoDB
        run: |
          python model/scrape.py
          python model/upload_to_mongodb.py -u "$MONGODB_URI"